#if !canImport(ObjectiveC)
import XCTest

extension AttributeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributeTests = [
        ("testName", testName),
        ("testWriteReadFixedString", testWriteReadFixedString),
        ("testWriteReadInt", testWriteReadInt),
        ("testWriteReadString", testWriteReadString),
    ]
}

extension DataspaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataspaceTests = [
        ("testDimensions", testDimensions),
        ("testMaxDimensions", testMaxDimensions),
        ("testSelect", testSelect),
    ]
}

extension FileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileTests = [
        ("testConvert", testConvert),
        ("testCreateDataset", testCreateDataset),
        ("testWriteRead", testWriteRead),
    ]
}

extension GroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GroupTests = [
        ("testName", testName),
        ("testObjectNames", testObjectNames),
    ]
}

extension HyperslabTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HyperslabTests = [
        ("testDoubleWriteRead", testDoubleWriteRead),
        ("testReadStringSlab", testReadStringSlab),
        ("testSlab2DReadDouble", testSlab2DReadDouble),
        ("testSlab2DReadString", testSlab2DReadString),
        ("testSlab3DRead", testSlab3DRead),
        ("testStringWriteRead", testStringWriteRead),
    ]
}

extension IndexingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndexingTests = [
        ("testAllReadDouble", testAllReadDouble),
        ("testAllReadInt", testAllReadInt),
        ("testAllReadString", testAllReadString),
        ("testSliceFirstTwoColumnsDouble", testSliceFirstTwoColumnsDouble),
        ("testSliceFirstTwoColumnsInt", testSliceFirstTwoColumnsInt),
        ("testSliceFirstTwoColumnsString", testSliceFirstTwoColumnsString),
        ("testSliceFirstTwoRowsDouble", testSliceFirstTwoRowsDouble),
        ("testSliceFirstTwoRowsInt", testSliceFirstTwoRowsInt),
        ("testSliceFirstTwoRowsString", testSliceFirstTwoRowsString),
        ("testSliceLastColumn", testSliceLastColumn),
        ("testSliceLastTwoColumns", testSliceLastTwoColumns),
        ("testSliceLastTwoColumnsOfLastTwoRows", testSliceLastTwoColumnsOfLastTwoRows),
        ("testSliceLastTwoRows", testSliceLastTwoRows),
        ("testSliceMiddleRow", testSliceMiddleRow),
        ("testSliceMiddleValue", testSliceMiddleValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AttributeTests.__allTests__AttributeTests),
        testCase(DataspaceTests.__allTests__DataspaceTests),
        testCase(FileTests.__allTests__FileTests),
        testCase(GroupTests.__allTests__GroupTests),
        testCase(HyperslabTests.__allTests__HyperslabTests),
        testCase(IndexingTests.__allTests__IndexingTests),
    ]
}
#endif
